import Foundation

// MARK: - AI providers the coach can run on
//
// Buddy's real-LLM coaching is BYO-key: the user brings a key from a provider
// they already pay for, and it stays on their device. This enum is the single
// place that knows which providers exist and what distinguishes them — the
// Keychain account the key lives under, the copy shown while connecting, and
// the key shape used to recognize a pasted key.
//
// Adding a provider means adding a case here plus a matching branch in the
// backend's `api/_lib/llm.ts`. Nothing else in the app enumerates providers.

/// One AI provider the user can connect a key for.
public enum CoachProvider: String, CaseIterable, Codable, Sendable {
    case anthropic
    case openai
    case gemini

    /// Product name, as the user knows it.
    public var displayName: String {
        switch self {
        case .anthropic: return "Anthropic"
        case .openai: return "OpenAI"
        case .gemini: return "Gemini"
        }
    }

    /// Which model family answers, in the user's words. Used in "Replies are
    /// generated by …" copy, where naming the model reads better than the vendor.
    public var modelFamily: String {
        switch self {
        case .anthropic: return "Claude"
        case .openai: return "GPT"
        case .gemini: return "Gemini"
        }
    }

    /// Keychain account holding this provider's key (via `TokenStoring`).
    ///
    /// `anthropic` deliberately keeps the original `coach-anthropic-key` account
    /// from when Anthropic was the only option, so an existing user's key is
    /// already where the multi-provider store looks. That is the whole migration:
    /// there is no copy step and nothing to re-enter.
    public var keyAccount: String {
        switch self {
        case .anthropic: return "coach-anthropic-key"
        case .openai: return "coach-openai-key"
        case .gemini: return "coach-gemini-key"
        }
    }

    /// Placeholder in the key field, showing the shape to expect.
    public var keyPlaceholder: String {
        switch self {
        case .anthropic: return "sk-ant-…"
        case .openai: return "sk-…"
        case .gemini: return "AIza…"
        }
    }

    /// "an Anthropic key" but "a Gemini key" — the indefinite article that reads
    /// correctly before this provider's name. Hardcoded per case rather than
    /// derived from the first letter, since the rule is about sound, not spelling.
    public var article: String {
        switch self {
        case .anthropic, .openai: return "an"
        case .gemini: return "a"
        }
    }

    /// Where the user creates a key for this provider.
    public var consoleURL: URL? {
        switch self {
        case .anthropic: return URL(string: "https://console.anthropic.com/settings/keys")
        case .openai: return URL(string: "https://platform.openai.com/api-keys")
        case .gemini: return URL(string: "https://aistudio.google.com/apikey")
        }
    }

    /// Stable display order: the provider Otterpace shipped with comes first, then
    /// the two added alongside it. `allCases` already yields this, but naming it
    /// keeps the UI from depending on declaration order by accident.
    public static var displayOrder: [CoachProvider] { allCases }

    // MARK: Recognizing a pasted key

    /// Best guess at which provider a pasted key belongs to, or nil when the shape
    /// matches none of them (the UI then asks the user to pick).
    ///
    /// Order matters: Anthropic keys start with `sk-ant-`, which is also a valid
    /// `sk-` prefix, so the more specific pattern has to be tested first or every
    /// Anthropic key would be misread as OpenAI.
    public static func detect(fromKey raw: String) -> CoachProvider? {
        let key = raw.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !key.isEmpty else { return nil }
        if key.hasPrefix("sk-ant-") { return .anthropic }
        if key.hasPrefix("AIza") { return .gemini }
        if key.hasPrefix("sk-") { return .openai }
        return nil
    }
}
