import SwiftUI

// One connected AI provider in the Settings AI Coach card: which provider it is,
// whether it is the one Buddy currently uses, and a control to disconnect it.
//
// Purely props-driven — it holds no store and reads no UserDefaults — so every
// combination (each provider, active or not, switchable or not) is capturable as
// an isolated component scenario without a Keychain entry.
struct CoachProviderRow: View {
    let provider: CoachProvider
    /// Whether this is the provider Buddy currently uses.
    let isActive: Bool
    /// False when this is the only connected provider: there is nothing to
    /// switch to, so the row stops taking taps.
    var canSwitch: Bool = true
    var onActivate: () -> Void = {}
    var onDisconnect: () -> Void = {}

    var body: some View {
        HStack(spacing: 12) {
            Button {
                guard !isActive else { return }
                onActivate()
            } label: {
                HStack(spacing: 12) {
                    Image(systemName: isActive ? "checkmark.circle.fill" : "circle")
                        .foregroundColor(isActive ? Palette.brand : Palette.subtle).frame(width: 24)
                    VStack(alignment: .leading, spacing: 2) {
                        Text(provider.displayName).font(Typography.body).foregroundColor(Palette.ink)
                        // Naming the model family ("generated by GPT") reads more
                        // concretely than repeating the vendor name.
                        Text(isActive
                             ? "Replies are generated by \(provider.modelFamily), using your key"
                             : "Connected")
                            .font(Typography.caption).foregroundColor(Palette.subtle)
                            .fixedSize(horizontal: false, vertical: true)
                    }
                    Spacer()
                }
                .contentShape(Rectangle())
            }
            .buttonStyle(.plain)
            // Deliberately NOT `.disabled`, which dims the row — greying out the
            // provider that IS active reads as broken rather than as "nothing to
            // switch to".
            .allowsHitTesting(canSwitch)
            .accessibilityElement(children: .combine)
            .accessibilityAddTraits(isActive ? [.isSelected] : [])
            .accessibilityLabel("\(provider.displayName)\(isActive ? ", active coach" : ", connected")")

            Button(action: onDisconnect) {
                Image(systemName: "xmark.circle")
                    .foregroundColor(Palette.brandDeep)
            }
            .buttonStyle(.plain)
            .accessibilityLabel("Disconnect \(provider.displayName)")
        }
        .padding(.vertical, 8)
    }
}
